{{- if and .Values.deploy ((.Values.credentials).bitwarden).enabled }}
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: {{ .Values.credentials.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
spec:
  data:
    {{ .Values.credentials.secretKey }}:
      secret: {{ .Values.credentials.bitwarden.secretName }}
{{- end }}
