{{- if .Values.deploy }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "webhook.selfSignedIssuer" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "webhook.rootCACertificate" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
spec:
  secretName: {{ include "webhook.rootCACertificate" . }}
  duration: 43800h
  issuerRef:
    name: {{ include "webhook.selfSignedIssuer" . }}
  commonName: "ca.{{ include "webhook.fullname" . }}.cert-manager"
  isCA: true
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "webhook.rootCAIssuer" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "webhook.rootCACertificate" . }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "webhook.servingCertificate" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
spec:
  secretName: {{ include "webhook.servingCertificate" . }}
  duration: 8760h
  renewBefore: 720h
  issuerRef:
    name: {{ include "webhook.rootCAIssuer" . }}
  dnsNames:
    - {{ include "webhook.fullname" . }}
    - {{ include "webhook.fullname" . }}.{{ .Release.Namespace }}
    - {{ include "webhook.fullname" . }}.{{ .Release.Namespace }}.svc
{{- end }}
